
version: 2

#add data sources from airbytes load
sources:
  - name: public #usually same name as schema
    database: data_warehouse
    schema: public
    tables:
      - name: src_salesorderdetail
      - name: src_salesperson

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
